version: "3.2"

services:
  # KAFKA
  # ports: 3000 - 3999
  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "3000:2181"
  my-kafka:
    image: "wurstmeister/kafka:0.10.2.0"
    ports:
      - "3100:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_CREATE_TOPICS: >
        user_names:4:1,user_follow_infos:4:1,user_scrape_errors:1:1,
        twitter-user_names:4:1,twitter-users_scraped:4:1,twitter-posts_scraped:4:1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # GRPC
  # ports: 4000 - 4999
  envoy-proxy:
    build: "./api/envoy-proxy"
    depends_on:
      - "grpc-server"
    ports:
      - "4000:8080"
  grpc-server:
    build:
      context: "."
      dockerfile: "./api/grpcserver/Dockerfile"
    environment:
      GRPC_POSTGRES_HOST: "postgres"
    ports:
      - "4100:10000"

  # INSTAGRAM SCRAPER
  insta_scraper:
    build: "insta_scraper/"
    image: "smag-insta_scraper"
    depends_on:
      - "my-kafka"
    environment:
      KAFKA_ADDRESS: "my-kafka:9092"

  # TWITTER SCRAPER
  twitter_scraper-users:
    build: "twitter_scraper/"
    image: "smag-twitter_scraper"
    command: ["-m", "twitterscraper.user_scraper"]
    depends_on:
      - "my-kafka"
    environment:
      KAFKA_HOST_PORT: "my-kafka:9092"
      KAFKA_FETCH_TOPIC: "twitter-user_names"
      KAFKA_INSERT_TOPIC: "twitter-users_scraped"
  twitter_scraper-tweets:
    build: "twitter_scraper/"
    image: "smag-twitter_scraper"
    command: ["-m", "twitterscraper.tweets_scraper"]
    depends_on:
      - "my-kafka"
    environment:
      KAFKA_HOST_PORT: "my-kafka:9092"
      KAFKA_FETCH_TOPIC: "twitter-user_names"
      KAFKA_INSERT_TOPIC: "twitter-tweets_scaped"
  kafka-seed:
    build: "twitter_scraper/"
    image: "smag-twitter_scraper"
    command: ["-m", "twitterscraper.insert_seed"]
    depends_on:
      - "my-kafka"
    environment:
      KAFKA_HOST_PORT: "my-kafka:9092"
      KAFKA_INSERT_TOPIC: "twitter-user_names"
      SEED_NAME: "urhengula5"
      SLEEP_SECONDS: "10"

  # POSTGRES
  # ports: 5000 - 5999
  postgres:
    image: "postgres:11.5"
    ports:
      - "5000:5432"
  pgadmin:
    image: "dpage/pgadmin4:4.13"
    ports:
      - "5100:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "my_awesome_email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "does_not_matter"
