version: "3.2"

services:

  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:0.10.2.0"
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_CREATE_TOPICS: >
        user_names:4:1,user_follow_infos:4:1,user_scrape_errors:1:1,
        twitter-user_names:4:1,twitter-users_scraped:4:1,twitter-posts_scraped:4:1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # neo4j:
  #   image: "neo4j:3.5.9"
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     NEO4J_HOME: "/var/lib/neo4j"
  #      NEO4J_AUTH: none
  postgres:
    image: postgres:11.5
    ports:
      - 5432:5432

  # INSTAGRAM SCRAPER
  insta_scraper:
    build: "insta_scraper/"
    image: "smag-insta_scraper"
    depends_on:
      - "kafka"
    environment:
      KAFKA_ADDRESS: "kafka:9092"

  # TWITTER SCRAPER
  twitter_scraper-users:
    build: "twitter_scraper/"
    image: "smag-twitter_scraper"
    command: ["-m", "twitterscraper.user_scraper"]
    depends_on:
      - "kafka"
    environment:
      KAFKA_HOST_PORT: "kafka:9092"
      KAFKA_FETCH_TOPIC: "twitter-user_names"
      KAFKA_INSERT_TOPIC: "twitter-users_scraped"
  twitter_scraper-tweets:
    build: "twitter_scraper/"
    image: "smag-twitter_scraper"
    command: ["-m", "twitterscraper.tweets_scraper"]
    depends_on:
      - "kafka"
    environment:
      KAFKA_HOST_PORT: "kafka:9092"
      KAFKA_FETCH_TOPIC: "twitter-user_names"
      KAFKA_INSERT_TOPIC: "twitter-tweets_scaped"
  kafka-seed:
    build: "twitter_scraper/"
    image: "smag-twitter_scraper"
    command: ["-m", "twitterscraper.insert_seed"]
    depends_on:
      - "kafka"
    environment:
      KAFKA_HOST_PORT: "kafka:9092"
      KAFKA_INSERT_TOPIC: "twitter-user_names"
      SEED_NAME: "urhengula5"
      SLEEP_SECONDS: "10"
