version: 2.1

executors:
  job-runner:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
jobs:
  tests:
    executor: job-runner
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go test -v ./...
  scraper-image:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh insta_user-scraper/Dockerfile codesmag/insta_user-scraper

  postgres-inserter-image:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh insta_postgres-inserter/Dockerfile codesmag/insta_postgres-inserter

  insta-comments-inserter:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh insta_comments-inserter/Dockerfile codesmag/insta_comments-inserter

  insta-comments-scraper:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh insta_comments-scraper/Dockerfile codesmag/insta_comments-scraper

  insta-posts-inserter:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh insta_posts-inserter/Dockerfile codesmag/insta-posts-inserter

  insta-posts-scraper:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh insta_posts-scraper/Dockerfile codesmag/insta_posts-scraper

  postgres-setup:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh debezium/kubernetes/Dockerfile codesmag/postgres-setup

  twitter_inserter_users:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh twitter_inserter_users/Dockerfile codesmag/twitter_inserter_users

  twitter_inserter_posts:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh twitter_inserter_posts/Dockerfile codesmag/twitter_inserter_posts

  twitter_user_names-filter:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh kafka/changestream/twitter_user_names-filter/Dockerfile codesmag/twitter_user_names-filter

  insta_user_names-filter:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh kafka/changestream/insta_user_names-filter/Dockerfile codesmag/insta_user_names_filter

  insta_post_pictures-filter:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh kafka/changestream/insta_post_pictures-filter/Dockerfile codesmag/insta_post_pictures_filter
  insta_pics_downloader:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh insta_pics-downloader/Dockerfile codesmag/insta_pics_downloader
  
  grpc-server:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh api/grpcserver/Dockerfile codesmag/grpc-server
  
  envoy-proxy:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh api/envoy-proxy/Dockerfile codesmag/envoy-proxy

  cli:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh cli/Dockerfile codesmag/cli
  aws_service:
    executor: job-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: ./build_and_upload_image.sh aws_service/Dockerfile codesmag/aws_service
  twitter_scraper:
    executor: job-runner
    environment:
      TWITTER_SCRAPER_IMAGE: codesmag/twitter_scraper
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $TWITTER_SCRAPER_IMAGE twitter_scraper/
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=$(date "+%Y-%m-%dT%H-%M-%S")
            docker tag $TWITTER_SCRAPER_IMAGE:latest $TWITTER_SCRAPER_IMAGE:$IMAGE_TAG
            docker push $TWITTER_SCRAPER_IMAGE:latest
            docker push $TWITTER_SCRAPER_IMAGE:$IMAGE_TAG

workflows:
  version: 2
  workflow:
    jobs:
      - tests
      - scraper-image:
          requires:
            - tests
          filters:
            branches:
              only: master
      - postgres-inserter-image:
          requires:
            - tests
          filters:
            branches:
              only: master
      - insta-comments-inserter:
          requires:
            - tests
          filters:
            branches:
              only: master
      - insta-comments-scraper:
          requires:
            - tests
          filters:
            branches:
              only: master
      - insta-posts-scraper:
          requires:
            - tests
          filters:
            branches:
              only: master
      - insta-posts-inserter:
          requires:
            - tests
          filters:
            branches:
              only: master
      - twitter_scraper:
          requires:
            - tests
          filters:
            branches:
              only: master
      - twitter_inserter_users:
          requires:
            - tests
          filters:
            branches:
              only: master
      - twitter_inserter_posts:
          requires:
            - tests
          filters:
            branches:
              only: master
      - postgres-setup:
          filters:
            branches:
              only: master
      - cli:
          filters:
            branches:
              only: master
      - aws_service:
          filters:
            branches:
              only: master
      - insta_user_names-filter:
          requires:
            - tests
          filters:
            branches:
              only: master
      - insta_post_pictures-filter:
          requires:
            - tests
          filters:
            branches:
              only: master
      - insta_pics_downloader:
          requires:
            - tests
          filters:
            branches:
              only: master
